#:schema https://yazi-rs.github.io/schemas/keymap.json

[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter directory or open file"

[[mgr.prepend_keymap]]
on = "p"
run = "plugin smart-paste"
desc = "Paste into hovered directory or current directory"

[[mgr.prepend_keymap]]
on = "T"
run = "plugin toggle-pane max-preview"
desc = "Maximize or restore preview"

[[mgr.prepend_keymap]]
on = "!"
for = "unix"
run = 'shell "$SHELL" --block'
desc = "Open shell here"

[[input.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Cancel input"
