#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json

dir_length = 1
sort_order = ["tmux", "config", "zoxide"]

[tui]
prompt = "> "
placeholder = "Filter sessions... "
show_icons = false
show_windows = true
preview = true
preview_width = 55
preview_min_width = 100
preview_border = "line"

[default_session]
preview_command = "eza --all --git --color=always {}"
